### ISSUE TITLE
UE5

### ISSUE THREAD

**Issue by Held0fTheWelt** [aws/aws-gamekit-unreal#10]
Just wanted to let you know.
This is also working in UE5.
Changes to do is to remove the engine definition in uplugin and to remove both namespaces GAMEKIT in gamekit_user_gameplay_data_models.h and rebuild that plugin
Cheers and Thanks !

**Comment by Held0fTheWelt** [comment]
Would love to have a UE5 branch to pull !

**Comment by amzn-proothia** [comment]
Hi HeldOfTheWelt,

I'm glad you were able to find a workaround. Thank you for sharing that here.

We will be working on supporting UE5 soon. We have another issue open as well for the same, which we have left open until we add UE5 support: https://github.com/aws/aws-gamekit-unreal/issues/5

Thank you!
