### ISSUE TITLE
Cant deploy Identity and Authentication with Facebook Login Mechanism enabled.

### ISSUE THREAD

**Issue by amar0k** [aws/aws-gamekit-unreal#11]
Hi i am attempting to deploy with facebook activated as a login mechanism however i get the below error on the AWS cloud formation stack.

`
Resource handler returned message: "'MemorySize' value failed to satisfy constraint: Member must have value less than or equal to 3008 (Service: Lambda, Status Code: 400, Request ID: ebcbe62b-f833-4cd5-af54-4f691fe777fe)" (RequestToken: f9c9cdf2-214f-e173-161b-4de53965f051, HandlerErrorCode: InvalidRequest)
`

It deploys fine without the facebook login mechanism enabled.

I am using Unreal Engine 4.27.2.

**Comment by AMZN-johnlaug** [comment]
Hello amar0k, 
Thank you for pointing out this issue. To help us investigate would you be able to share the following: 

1. IDE and Version [e.g. Visual Studio 2019 16.11.7]
2. OS and Version that you are developing on: [e.g. Windows 10]
3. Region you are trying to deploy in.

**Comment by amar0k** [comment]
@AMZN-johnlaug Hi John,

Thanks for the reply this was resolved by AWS increasing the limit to 10 GB for Lambda on my account.

Thanks.

**Comment by AMZN-johnlaug** [comment]
Hi amar0k,
That's excellent news. 
I have found the problem in our code and we will work on a fix in a future release.

Thank you for providing the references, that'll be helpful for anyone else running into this.

**Comment by AMZN-johnlaug** [comment]
In the meantime, if you want to fix this yourself (without relying on the limit increase) 
You can remove the MemorySize line here: 
https://github.com/aws/aws-gamekit-unreal/blob/main/AwsGameKit/Resources/cloudResources/cloudformation/identity/cloudFormation.yml#L312

This lambda shouldn't need that much memory and should work fine with the default.

**Comment by amar0k** [comment]
> In the meantime, if you want to fix this yourself (without relying on the limit increase) You can remove the MemorySize line here: https://github.com/aws/aws-gamekit-unreal/blob/main/AwsGameKit/Resources/cloudResources/cloudformation/identity/cloudFormation.yml#L312
> 
> This lambda shouldn't need that much memory and should work fine with the default.

Thanks @AMZN-johnlaug ! Appreciate the help.

**Comment by DJAYZZZ** [comment]
cant deploy fb login Login Mechanism getting these errors and then it starts to rollback pls help (thanks in advance)

~ FbCallbackHandlerApiResource | CREATE_FAILED: Resource creation cancelled
~ gamekit-dev-gkone-identity: GetUserLambdaHandler | UPDATE_COMPLETE: 
~ gamekit-dev-gkone-identity: PollFacebookLoginCompletionLambda | DELETE_COMPLETE: 
~ gamekit-dev-gkone-identity: FbLoginUrlHandlerApiResource | DELETE_COMPLETE

**Comment by DJAYZZZ** [comment]
Logical ID          :   FacebookUserPoolIdentityProvider
Status                :   CREATE_FAILED
Status Reason   :     v6.0 is not a valid value for api_version (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error 
                                Code: InvalidParameterException; Request ID: be5cd116-9240-450b-82d4-c02c960c39e3; Proxy: null)

Unreal error : Error : FeatureResourceManager::CreateOrUpdateResources() for Identity And Authentication feature: Could not 
                                 create resources.
Thank you @buchandl  For the support

**Comment by DJAYZZZ** [comment]
Yes , Changing v6.0 to v12.0 solved the problem.

I did not find the directory and don't know how to update it (instance template)?
[your_unreal_project]/[game_alias]/[aws_region]/cloudformation/identity/cloudformation.yml
did you mean? 
[Unreal_project]\[Unreal_project]\dev\cloudformation\identity\cloudformation.yml
in my case
gkone/gkone/dev/cloudformation/identity/cloudformation.yml

I was just testing and was not afraid of losing any data
so I deleted all resources from Unreal and  from AWS console also. 
and Deployed it again from Unreal. that worked with same project
Thank you @buchandl

**Comment by amzn-adrian** [comment]
Hi,

We've released a new version of the plugin that fixes both MemorySize and api_version issues. You can find the plugin [here](https://github.com/aws/aws-gamekit-unreal/releases/tag/v2.0.0).
