### ISSUE TITLE
Can't package 32 and 64 bit combined Android App Bundle

### ISSUE THREAD

**Issue by Byambasurenn** [aws/aws-gamekit-unreal#19]
Hello

I am trying to upload my app to google play store. But I can't package an Android App Bundle that combines 32 and 64 bits. I can't build the package while enabling both "Support armv7" and "Support arm64" in project settings.

I opened [this](https://github.com/aws/aws-gamekit-unreal/issues/16#issuecomment-1233178401) issue before. But it doesn't resolve my problem.
Since August 2021, play store doesn't support APK and separate uploading for 32/64 bit. [Source](https://android-developers.googleblog.com/2021/06/the-future-of-android-app-bundles-is.html)

thanks
Byambasuren

**Comment by AMZN-johnlaug** [comment]
Hello, 
in order to investigate this further, would you be able to to list the following: 
- Which Android platforms are you building for? (Android 11, Android 12)

I also recommend looking over this article and checking if the ABI Split can resolve your issue.
https://docs.unrealengine.com/5.0/en-US/packaging-android-projects-in-unreal-engine/

If you still see the same issue, would you be able to share the log or error message?

**Comment by Byambasurenn** [comment]
Hello,

Thanks for the reply, I really appreciate it.
- I am building for an Android version 12.
I looked into the article and checked it in the editor, it seems ABI Split is enabled by default. It couldn't resolve my issue.
I want to be able to build an android package while enabling both "Support armv7" and "Support arm64" in project settings. But there are two different GamekitSDK versions, and android 32bit, 64bit are separated in each version. It needs to be combined.
Here are log for building package:
`WindowsPlatformFactory.RegisterBuildPlatforms: UnrealBuildTool.WindowsPlatformSDK using manually installed SDK BuildMode.Execute: Command line: "H:\UE4\UnrealEngine\Engine\Binaries\DotNET\UnrealBuildTool.exe" Verse Android Development -Project="H:\Git Projects\VerseMain\verse\Verse.uproject" "H:\Git Projects\VerseMain\verse\Verse.uproject" -NoUBTMakefiles -remoteini="H:\Git Projects\VerseMain\verse" -skipdeploy -Manifest=H:\UE4\UnrealEngine\Engine\Intermediate\Build\Manifest.xml -NoHotReload -log="H:\UE4\UnrealEngine\Engine\Programs\AutomationTool\Saved\Logs\UBT-Verse-Android-Development.txt" GitSourceFileWorkingSet..ctor: Using 'git status' to determine working set for adaptive non-unity build (H:\UE4\UnrealEngine). GitSourceFileWorkingSet..ctor: Using 'git status' to determine working set for adaptive non-unity build (H:\Git Projects\VerseMain\verse). UEBuildTarget.AddPlugin: Enabling plugin 'GLTFImporter' (referenced via Verse.uproject) UEBuildTarget.AddPlugin: Enabling plugin 'GameLiftServerSDK' (referenced via Verse.uproject) UEBuildTarget.AddPlugin: Enabling plugin 'ChunkCore' (referenced via Verse.uproject) UEBuildTarget.AddPlugin: Enabling plugin 'ChunkDownloader' (referenced via Verse.uproject -> ChunkCore.uplugin) UEBuildTarget.AddPlugin: Enabling plugin 'StereoPanoramicPlayer' (referenced via Verse.uproject) UEBuildTarget.AddPlugin: Enabling plugin 'ProceduralMeshComponent' (referenced via Verse.uproject -> StereoPanoramicPlayer.uplugin) UEBuildTarget.AddPlugin: Enabling plugin 'UniversalVoiceChatPro' (referenced via Verse.uproject) UEBuildTarget.AddPlugin: Enabling plugin 'AudioCapture' (referenced via Verse.uproject -> UniversalVoiceChatPro.uplugin) UEBuildTarget.AddPlugin: Enabling plugin 'VaRest' (referenced via Verse.uproject) UEBuildTarget.AddPlugin: Enabling plugin 'Plugin' (referenced via Verse.uproject) UEBuildTarget.AddPlugin: Enabling plugin 'AwsGameKit' (referenced via Verse.uproject) UEBuildTarget.AddPlugin: Enabling plugin 'TickOptToolkit' (referenced via Verse.uproject) UEBuildTarget.AddPlugin: Enabling plugin 'CommonUI' (referenced via Verse.uproject) UEBuildTarget.AddPlugin: Enabling plugin 'GameplayTagsEditor' (referenced via Verse.uproject -> CommonUI.uplugin) UEBuildTarget.AddPlugin: Enabling plugin 'LowEntryExtStdLib' (referenced via Verse.uproject) UEBuildTarget.AddPlugin: Enabling plugin 'glTFRuntime' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'Paper2D' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'AISupport' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'EnvironmentQueryEditor' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'LightPropagationVolume' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'CameraShakePreviewer' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'GameplayCameras' (referenced via default plugins -> CameraShakePreviewer.uplugin) UEBuildTarget.AddPlugin: Enabling plugin 'TemplateSequence' (referenced via default plugins -> CameraShakePreviewer.uplugin -> GameplayCameras.uplugin) UEBuildTarget.AddPlugin: Enabling plugin 'LevelSequenceEditor' (referenced via default plugins -> CameraShakePreviewer.uplugin -> GameplayCameras.uplugin -> TemplateSequence.uplugin) UEBuildTarget.AddPlugin: Enabling plugin 'OodleData' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'OodleNetwork' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'AnimationSharing' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'SignificanceManager' (referenced via default plugins -> AnimationSharing.uplugin) UEBuildTarget.AddPlugin: Enabling plugin 'CLionSourceCodeAccess' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'CodeLiteSourceCodeAccess' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'GitSourceControl' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'KDevelopSourceCodeAccess' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'NullSourceCodeAccess' (referenced via default plugins) UEBuildTarget.AddPlugin: Ignoring plugin 'PixWinPlugin' (referenced via default plugins) due to unsupported target platform. UEBuildTarget.AddPlugin: Enabling plugin 'PlasticSourceControl' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'PluginUtils' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'PropertyAccessNode' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'PropertyAccessEditor' (referenced via default plugins -> PropertyAccessNode.uplugin) UEBuildTarget.AddPlugin: Enabling plugin 'TextureFormatOodle' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'UObjectPlugin' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'VisualStudioCodeSourceCodeAccess' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'VisualStudioSourceCodeAccess' (referenced via default plugins) UEBuildTarget.AddPlugin: Ignoring plugin 'XCodeSourceCodeAccess' (referenced via default plugins) due to unsupported target platform. UEBuildTarget.AddPlugin: Enabling plugin 'AssetManagerEditor' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'ContentBrowserAssetDataSource' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'ContentBrowserClassDataSource' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'CryptoKeys' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'CurveEditorTools' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'DataValidation' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'FacialAnimation' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'GeometryMode' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'MacGraphicsSwitching' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'MaterialAnalyzer' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'MobileLauncherProfileWizard' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'PluginBrowser' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'DatasmithContent' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'VariantManagerContent' (referenced via default plugins -> DatasmithContent.uplugin) UEBuildTarget.AddPlugin: Enabling plugin 'AutomationUtils' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'ScreenshotTools' (referenced via default plugins -> AutomationUtils.uplugin) UEBuildTarget.AddPlugin: Enabling plugin 'BackChannel' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'ChaosClothEditor' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'ChaosCloth' (referenced via default plugins -> ChaosClothEditor.uplugin) UEBuildTarget.AddPlugin: Enabling plugin 'ChaosEditor' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'PlanarCut' (referenced via default plugins -> ChaosEditor.uplugin) UEBuildTarget.AddPlugin: Enabling plugin 'GeometryProcessing' (referenced via default plugins -> ChaosEditor.uplugin -> PlanarCut.uplugin) UEBuildTarget.AddPlugin: Enabling plugin 'EditableMesh' (referenced via default plugins -> ChaosEditor.uplugin) UEBuildTarget.AddPlugin: Enabling plugin 'GeometryCollectionPlugin' (referenced via default plugins -> ChaosEditor.uplugin) UEBuildTarget.AddPlugin: Enabling plugin 'ChaosSolverPlugin' (referenced via default plugins -> ChaosEditor.uplugin -> GeometryCollectionPlugin.uplugin) UEBuildTarget.AddPlugin: Enabling plugin 'ChaosNiagara' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'Niagara' (referenced via default plugins -> ChaosNiagara.uplugin) UEBuildTarget.AddPlugin: Enabling plugin 'PythonScriptPlugin' (referenced via default plugins -> ChaosNiagara.uplugin -> Niagara.uplugin) UEBuildTarget.AddPlugin: Ignoring plugin 'ContentBrowserFileDataSource' (referenced via default plugins -> ChaosNiagara.uplugin -> Niagara.uplugin -> PythonScriptPlugin.uplugin) for platform/configuration UEBuildTarget.AddPlugin: Enabling plugin 'CharacterAI' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'GeometryCache' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'MotoSynth' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'OpenImageDenoise' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'PlatformCrypto' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'ProxyLODPlugin' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'SkeletalReduction' (referenced via default plugins) UEBuildTarget.AddPlugin: Ignoring plugin 'LuminPlatformFeatures' (referenced via default plugins) due to unsupported target platform. UEBuildTarget.AddPlugin: Ignoring plugin 'MagicLeapMedia' (referenced via default plugins) due to unsupported target platform. UEBuildTarget.AddPlugin: Ignoring plugin 'MagicLeapPassableWorld' (referenced via default plugins) due to unsupported target platform. UEBuildTarget.AddPlugin: Ignoring plugin 'MagicLeap' (referenced via default plugins) due to unsupported target platform. UEBuildTarget.AddPlugin: Enabling plugin 'MLSDK' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'AndroidMedia' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'AvfMedia' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'ImgMedia' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'MediaCompositing' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'MediaPlayerEditor' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'WmfMedia' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'MeshPainting' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'TcpMessaging' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'UdpMessaging' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'ActorSequence' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'MatineeToLevelSequence' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'OnlineSubsystemGooglePlay' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'OnlineSubsystem' (referenced via default plugins -> OnlineSubsystemGooglePlay.uplugin) UEBuildTarget.AddPlugin: Enabling plugin 'AndroidPermission' (referenced via default plugins -> OnlineSubsystemGooglePlay.uplugin) UEBuildTarget.AddPlugin: Ignoring plugin 'OnlineSubsystemIOS' (referenced via default plugins) due to unsupported target platform. UEBuildTarget.AddPlugin: Enabling plugin 'OnlineSubsystemNull' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'OnlineSubsystemUtils' (referenced via default plugins -> OnlineSubsystemNull.uplugin) UEBuildTarget.AddPlugin: Enabling plugin 'LauncherChunkInstaller' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'ActorLayerUtilities' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'AndroidDeviceProfileSelector' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'AndroidMoviePlayer' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'AppleImageUtils' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'AssetTags' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'CableComponent' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'CustomMeshComponent' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'ExampleDeviceProfileSelector' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'GoogleCloudMessaging' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'GooglePAD' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'IOSDeviceProfileSelector' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'LinuxDeviceProfileSelector' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'LocationServicesBPLibrary' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'MobilePatchingUtils' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'OculusVR' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'OpenXREyeTracker' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'OpenXR' (referenced via default plugins -> OpenXREyeTracker.uplugin) UEBuildTarget.AddPlugin: Enabling plugin 'OpenXRHandTracking' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'LiveLink' (referenced via default plugins -> OpenXRHandTracking.uplugin) UEBuildTarget.AddPlugin: Enabling plugin 'Takes' (referenced via default plugins -> OpenXRHandTracking.uplugin -> LiveLink.uplugin) UEBuildTarget.AddPlugin: Enabling plugin 'PhysXVehicles' (referenced via default plugins) UEBuildTarget.AddPlugin: Ignoring plugin 'PostSplashScreen' (referenced via default plugins) due to unsupported target platform. UEBuildTarget.AddPlugin: Enabling plugin 'RuntimePhysXCooking' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'SoundFields' (referenced via default plugins) UEBuildTarget.AddPlugin: Ignoring plugin 'SteamVR' (referenced via default plugins) due to unsupported target platform. UEBuildTarget.AddPlugin: Enabling plugin 'Synthesis' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'AudioSynesthesia' (referenced via default plugins -> Synthesis.uplugin) UEBuildTarget.AddPlugin: Enabling plugin 'WebMMoviePlayer' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'WebMMedia' (referenced via default plugins -> WebMMoviePlayer.uplugin) UEBuildTarget.AddPlugin: Enabling plugin 'WindowsMoviePlayer' (referenced via default plugins) UEBuildTarget.AddPlugin: Enabling plugin 'XGEController' (referenced via default plugins) AndroidPlatform.SetUpSpecificEnvironment: PLATFORM_ANDROID_NDK_VERSION = 210500 AndroidPlatform.SetUpSpecificEnvironment: NDK toolchain: r21e, NDK version: 24, GccVersion: 4.9, ClangVersion: 9.0.9 AndroidToolChain.CompileCPPFiles: Compiling Native 32-bit code with NDK API 'android-24' AndroidToolChain.CompileCPPFiles: Compiling Native 64-bit code with NDK API 'android-24' UEBuildTarget.GenerateManifest: Writing manifest to H:\UE4\UnrealEngine\Engine\Intermediate\Build\Manifest.xml HotReload.IsLiveCodingSessionActive: Checking for live coding mutex: Global\LiveCoding_H++Git Projects+VerseMain+verse+Binaries+Android+Verse-armv7.so ActionGraph.IsActionOutdated: Verse-arm64.so: Produced item "Verse-arm64.so" doesn't exist. ActionGraph.IsActionOutdated: Verse.target: Prerequisite Verse-arm64.so is produced by outdated action. BuildMode.Build: Building Verse... ParallelExecutor.ExecuteActions: Building 2 actions with 8 processes... ParallelExecutor.ExecuteActions: [1/2] Verse-arm64.so ParallelExecutor.ExecuteActions: ld.lld: error: H:/Git Projects/VerseMain/verse/Plugins/AwsGameKit/Libraries/Android/Debug\libcrypto.a(init.c.o) is incompatible with aarch64linux ParallelExecutor.ExecuteActions: ld.lld: error: H:/Git Projects/VerseMain/verse/Plugins/AwsGameKit/Libraries/Android/Debug\libcrypto.a(bio_lib.c.o) is incompatible with aarch64linux ParallelExecutor.ExecuteActions: ld.lld: error: H:/Git Projects/VerseMain/verse/Plugins/AwsGameKit/Libraries/Android/Debug\libcrypto.a(bss_mem.c.o) is incompatible with aarch64linux ParallelExecutor.ExecuteActions: ld.lld: error: H:/Git Projects/VerseMain/verse/Plugins/AwsGameKit/Libraries/Android/Debug\libcrypto.a(bn_lib.c.o) is incompatible with aarch64linux ParallelExecutor.ExecuteActions: ld.lld: error: H:/Git Projects/VerseMain/verse/Plugins/AwsGameKit/Libraries/Android/Debug\libcrypto.a(conf_mall.c.o) is incompatible with aarch64linux ParallelExecutor.ExecuteActions: ld.lld: error: H:/Git Projects/VerseMain/verse/Plugins/AwsGameKit/Libraries/Android/Debug\libcrypto.a(conf_mod.c.o) is incompatible with aarch64linux ParallelExecutor.ExecuteActions: ld.lld: error: H:/Git Projects/VerseMain/verse/Plugins/AwsGameKit/Libraries/Android/Debug\libcrypto.a(err.c.o) is incompatible with aarch64linux ParallelExecutor.ExecuteActions: ld.lld: error: H:/Git Projects/VerseMain/verse/Plugins/AwsGameKit/Libraries/Android/Debug\libcrypto.a(digest.c.o) is incompatible with aarch64linux ParallelExecutor.ExecuteActions: ld.lld: error: H:/Git Projects/VerseMain/verse/Plugins/AwsGameKit/Libraries/Android/Debug\libcrypto.a(e_aes.c.o) is incompatible with aarch64linux ParallelExecutor.ExecuteActions: ld.lld: error: H:/Git Projects/VerseMain/verse/Plugins/AwsGameKit/Libraries/Android/Debug\libcrypto.a(evp_enc.c.o) is incompatible with aarch64linux ParallelExecutor.ExecuteActions: ld.lld: error: H:/Git Projects/VerseMain/verse/Plugins/AwsGameKit/Libraries/Android/Debug\libcrypto.a(evp_lib.c.o) is incompatible with aarch64linux ParallelExecutor.ExecuteActions: ld.lld: error: H:/Git Projects/VerseMain/verse/Plugins/AwsGameKit/Libraries/Android/Debug\libcrypto.a(m_sha1.c.o) is incompatible with aarch64linux ParallelExecutor.ExecuteActions: ld.lld: error: H:/Git Projects/VerseMain/verse/Plugins/AwsGameKit/Libraries/Android/Debug\libcrypto.a(m_sigver.c.o) is incompatible with aarch64linux ParallelExecutor.ExecuteActions: ld.lld: error: H:/Git Projects/VerseMain/verse/Plugins/AwsGameKit/Libraries/Android/Debug\libcrypto.a(names.c.o) is incompatible with aarch64linux ParallelExecutor.ExecuteActions: ld.lld: error: H:/Git Projects/VerseMain/verse/Plugins/AwsGameKit/Libraries/Android/Debug\libcrypto.a(p_lib.c.o) is incompatible with aarch64linux ParallelExecutor.ExecuteActions: ld.lld: error: H:/Git Projects/VerseMain/verse/Plugins/AwsGameKit/Libraries/Android/Debug\libcrypto.a(pem_x509.c.o) is incompatible with aarch64linux ParallelExecutor.ExecuteActions: ld.lld: error: H:/Git Projects/VerseMain/verse/Plugins/AwsGameKit/Libraries/Android/Debug\libcrypto.a(rand_lib.c.o) is incompatible with aarch64linux ParallelExecutor.ExecuteActions: ld.lld: error: H:/Git Projects/VerseMain/verse/Plugins/AwsGameKit/Libraries/Android/Debug\libcrypto.a(rsa_asn1.c.o) is incompatible with aarch64linux ParallelExecutor.ExecuteActions: ld.lld: error: H:/Git Projects/VerseMain/verse/Plugins/AwsGameKit/Libraries/Android/Debug\libcrypto.a(rsa_crpt.c.o) is incompatible with aarch64linux ParallelExecutor.ExecuteActions: ld.lld: error: H:/Git Projects/VerseMain/verse/Plugins/AwsGameKit/Libraries/Android/Debug\libcrypto.a(rsa_lib.c.o) is incompatible with aarch64linux ParallelExecutor.ExecuteActions: ld.lld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors) ParallelExecutor.ExecuteActions: clang++: error: linker command failed with exit code 1 (use -v to see invocation) UnrealBuildTool.Main: CompilationResultException: Error: OtherCompilationError UnrealBuildTool.Main: at UnrealBuildTool.ActionGraph.ExecuteActions(BuildConfiguration BuildConfiguration, List1 ActionsToExecute) in H:\UE4\UnrealEngine\Engine\Source\Programs\UnrealBuildTool\System\ActionGraph.cs:line 230
UnrealBuildTool.Main: at UnrealBuildTool.BuildMode.Build(TargetMakefile[] Makefiles, List1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile) in H:\UE4\UnrealEngine\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 485 UnrealBuildTool.Main: at UnrealBuildTool.BuildMode.Execute(CommandLineArguments Arguments) in H:\UE4\UnrealEngine\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 226 UnrealBuildTool.Main: at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in H:\UE4\UnrealEngine\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 557 Timeline.Print: Timeline: Timeline.Print: Timeline.Print: [ 0.000] Timeline.Print: [ 0.017](+0.002) FileMetadataPrefetch.QueueEngineDirectory() Timeline.Print: [ 0.020](+0.047) XmlConfig.ReadConfigFiles() Timeline.Print: [ 0.068](+0.000) SingleInstanceMutex.Acquire() Timeline.Print: [ 0.068](+0.428) UEBuildPlatform.RegisterPlatforms() Timeline.Print: 0.069 [ 0.000](+0.029) Initializing InstalledPlatformInfo Timeline.Print: 0.099 [ 0.030](+0.000) Querying types Timeline.Print: 0.100 [ 0.032](+0.024) MacPlatformFactory Timeline.Print: 0.125 [ 0.056](+0.005) TVOSPlatformFactory Timeline.Print: 0.130 [ 0.062](+0.006) AndroidPlatformFactory Timeline.Print: 0.137 [ 0.068](+0.001) HoloLensPlatformFactory Timeline.Print: 0.138 [ 0.070](+0.003) IOSPlatformFactory Timeline.Print: 0.141 [ 0.073](+0.005) LinuxPlatformFactory Timeline.Print: 0.147 [ 0.078](+0.348) LuminPlatformFactory Timeline.Print: 0.496 [ 0.427](+0.001) WindowsPlatformFactory Timeline.Print: [ 0.505](+0.003) DeleteJunk() Timeline.Print: [ 0.509](+0.012) TargetDescriptor.ParseCommandLine() Timeline.Print: [ 0.521](+0.356) <unknown> Timeline.Print: [ 0.878](+0.815) UEBuildTarget.Create() Timeline.Print: 0.883 [ 0.004](+0.219) RulesCompiler.CreateTargetRulesAssembly() Timeline.Print: 0.883 0.004 [ 0.000](+0.113) <unknown> Timeline.Print: 0.996 0.118 [ 0.113](+0.041) Finding engine modules Timeline.Print: 1.038 0.160 [ 0.155](+0.007) Finding plugin modules Timeline.Print: 1.045 0.167 [ 0.162](+0.041) <unknown> Timeline.Print: 1.087 0.208 [ 0.203](+0.006) Finding program modules Timeline.Print: 1.093 0.215 [ 0.210](+0.001) Finding program targets Timeline.Print: 1.102 [ 0.224](+0.028) RulesAssembly.CreateTargetRules() Timeline.Print: 1.140 [ 0.262](+0.218) UEBuildTarget constructor Timeline.Print: 1.144 0.265 [ 0.003](+0.212) Reading source file metadata cache Timeline.Print: 1.356 0.477 [ 0.215](+0.001) Reading source file metadata cache Timeline.Print: 1.358 [ 0.480](+0.335) UEBuildTarget.PreBuildSetup() Timeline.Print: [ 1.697](+6.552) UEBuildTarget.Build() Timeline.Print: 1.697 [ 0.000](+0.162) <unknown> Timeline.Print: 1.860 [ 0.162](+0.030) ExternalExecution.SetupUObjectModules() Timeline.Print: 1.890 [ 0.193](+0.051) <unknown> Timeline.Print: 1.942 [ 0.244](+0.042) ExternalExecution.UpdateDirectoryTimestamps() Timeline.Print: 1.985 [ 0.287](+0.033) <unknown> Timeline.Print: 2.019 [ 0.321](+6.180) UEBuildBinary.Build() Timeline.Print: 8.199 [ 6.501](+0.050) <unknown> Timeline.Print: [ 8.257](+0.003) ActionGraph.CheckPathLengths Timeline.Print: [ 8.275](+0.000) Reading action history Timeline.Print: [ 8.275](+0.184) Reading dependency cache Timeline.Print: [ 8.462](+0.065) Prefetching include dependencies Timeline.Print: [ 8.527](+0.122) Cache outdated actions Timeline.Print: [ 8.657](+1.092) ActionGraph.ExecuteActions() Timeline.Print: [ 9.750](+0.594) <unknown> Timeline.Print: [10.345](+0.000) FileMetadataPrefetch.Stop() Timeline.Print: [10.347]`

**Comment by amzn-adrian** [comment]
Hi Byambasurenn,

A way to combine the libraries would be to modify your local AwsGameKitCore.Build.cs so that it adds libraries for both architectures. An example of this is in the updated [AwsGameKitCore.Build.cs](https://github.com/aws/aws-gamekit-unreal/blob/v2.0.0/AwsGameKit/Source/AwsGameKitCore/AwsGameKitCore.Build.cs). If you don't want to update to the latest version of the plugin, you can copy the content of the build script and it should let you package for both architectures.
