### ISSUE TITLE
awsGameKitClientConfig.yml in shipping package

### ISSUE THREAD

**Issue by 1123581321345589144233377** [aws/aws-gamekit-unreal#20]
Hello Gamekit Team,

I built windows shipping package. And there was "awsGameKitClientConfig.yml"(WindowsNoEditor\{ProjectName}\Content\GameKitConfig\awsGameKitClientConfig.yml) config file. I don't want this file to be easily accessible for clients. Is there a way to read these config properties from source code? Or is it ok to be visible to the client?

thanks

**Comment by amzn-adrian** [comment]
Hi,

An option is to hard code the properties as a newline-separated, null-terminated string that has the same contents as the config file and pass it to `AwsGameKitSessionManagerWrapper::GameKitSessionManagerReloadConfigContents()` inside `AwsGameKitSessionManagerWrapper::ReloadConfig()`. Both functions are in [AwsGameKitSessionManagerWrapper.cpp](https://github.com/aws/aws-gamekit-unreal/blob/main/AwsGameKit/Source/AwsGameKitRuntime/Private/SessionManager/AwsGameKitSessionManagerWrapper.cpp).
