### ISSUE TITLE
Project Settings Stuck

### ISSUE THREAD

**Issue by zorigoo0128** [aws/aws-gamekit-unreal#4]
It stucks editor for 1min when **Project Settings** loaded

**Comment by plamazon** [comment]
Hello zorigoo0128, 

I'm sorry to hear that you are having this issue. We are researching this. To help us, would you please provide some additional information?

1. Are you behind a firewall? If yes, then does the issue still occur if you disable the firewall?
2. Are you using a VPN? If yes, then does the issue still occur if you are not using the VPN?
3. Does the issue occur immediately after installing the GameKit plugin, before changing any of the GameKit settings? Or does the issue occur after you have, for example, entered a game title and/or credentials for your GameKit project?

**Comment by zorigoo0128** [comment]
Hello,
1. Firewall is off
2. no VPN
3. I just noticed that initializing aws gamekit services delays engine for few seconds
4. Here is some logs when initializing aws gamekit 


LogAwsGameKit: Warning: [0000022F050578A0@3332]~ Lambda Layer hash parameter not found for layer CommonLambdaLayer. This is expected when you deploy your first GameKit feature.
LogAwsGameKit: Display: [0000022F050578A0@3332]~ Zip file C:\Users\User\AppData\Local\Temp\gamekit_layers\2285030\main/CommonLambdaLayer.zip created
LogAwsGameKit: Warning: [0000022F050578A0@3332]~ Lambda Layer hash parameter not found for layer CryptoLambdaLayer. This is expected when you deploy your first GameKit feature.
LogAwsGameKit: Display: [0000022F050578A0@3332]~ Zip file C:\Users\User\AppData\Local\Temp\gamekit_layers\2285030\main/CryptoLambdaLayer.zip created
LogAwsGameKit: Warning: [0000022F050578A0@3332]~ Lambda Layer hash parameter not found for layer ImageProcessingLambdaLayer. This is expected when you deploy your first GameKit feature.
LogAwsGameKit: Display: [0000022F050578A0@3332]~ Zip file C:\Users\User\AppData\Local\Temp\gamekit_layers\2285030\main/ImageProcessingLambdaLayer.zip created
LogAwsGameKit: Warning: [0000022F050578A0@3332]~ Lambda Layer hash parameter not found for layer ResourceManagementLambdaLayer. This is expected when you deploy your first GameKit feature.

**Comment by plamazon** [comment]
Hello zorigoo0128,

Thank you for the quick response. We are continuing to look into how to reproduce the issue. Some additional questions
1. Are you able to deploy any of the GameKit Identity and Authentication feature? https://docs.aws.amazon.com/gamekit/latest/DevGuide/identity-auth-deploying.html 
2. If you are able to deploy the above feature, are you able to run any of the examples for that feature? https://docs.aws.amazon.com/gamekit/latest/DevGuide/identity-auth-examples.html#identity-auth-examples-cpp 
3. Does this issue happen only once, or are you noticing a delay every time the engine is opened/started?

**Comment by zorigoo0128** [comment]
Hello Plamazon
1. Editor completely not responding to any interact
2. My spec is i9 10gen (20cpu), 16gb RAM, Windows 11 Pro (64-bit), RTX 2070s GPU, No VM, average down|up internet speed is 50mbps
3. I deployed Identity & Authentication, User Gameplay Data. 
4. not yet
5. It delays every time engine started and  "_initializing bundles_" process also delays for a few seconds during gameplay 

Also, some weird errors appeared during packaging process. Could you see it?

`UATHelper: Packaging (Windows (64-bit)):   LogThreadingWindows: Error: Runnable thread TaskGraphThreadBP 36 crashed.
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: begin: stack for UAT
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: === Critical error: ===
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error:
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: Assertion failed: IsValid() [File:E:\Epic Games\UE_4.27\Engine\Source\Runtime\Core\Public\Templates/SharedPointer.h] [Line: 890]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error:
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error:
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error:
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffdef29478c KERNELBASE.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffd753e0216 UE4Editor-Core.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffd753e4218 UE4Editor-Core.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffd7510242d UE4Editor-Core.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffd75056a45 UE4Editor-Core.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffd750580a0 UE4Editor-Core.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffd37ca337b UE4Editor-AwsGameKitEditor-0001.dll!<lambda_7499ae760172cc091670ab4c7b0998ab>::operator()() [E:\UnrealProjects\AWSPluginTest\Plugins\AwsGameKit\Source\AwsGameKitEditor\Private\AwsGameKitEditor.cpp:166]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffd74e4f045 UE4Editor-Core.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffd74e61507 UE4Editor-Core.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffd74e62860 UE4Editor-Core.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffd74e69aa5 UE4Editor-Core.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffd753fff0b UE4Editor-Core.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffd753f7050 UE4Editor-Core.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffdf09f54e0 KERNEL32.DLL!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffdf1a2485b ntdll.dll!UnknownFunction []`

**Comment by plamazon** [comment]
Hello zorigoo0128,

Thank you again for your quick response and help in trying to resolve this issue. We are still researching into how to reproduce the issue, we will reply on this post once we have an update. In the meantime, a couple suggestion to try, if you have not already:
- please try a clean install of our plugin in a new Unreal project. Please redownload both https://github.com/aws/aws-gamekit and https://github.com/aws/aws-gamekit-unreal , rebuild and copy over the DLLs from aws-gamekit into the aws-gamekit-unreal plugin (using the readme instructions), then rebuild your new Unreal project code.  
- alternatively, instead of installing our plugin through our GitHub packages, please try installing the plugin from our AWS website https://aws.amazon.com/gamekit/

**Comment by AMZN-kevomara** [comment]
Hi zorigoo0128,

I just want to let you know I'm looking into this now, and I'll post an update if there is anything important to share.

**Comment by AMZN-kevomara** [comment]
Hi zorigoo0128,

We've been able to reproduce the freezing issue on two devices - a Windows 10 computer and a Windows 11 computer.

We are working on fixing this. Thank you again for reporting this issue.

**Comment by amzn-adrian** [comment]
Hi zorigoo0128.

We were able to fix this issue and the fix will be part of our next release. We'll post an update when the next release ships.

**Comment by amzn-adrian** [comment]
Hi zorigoo0128. We've published our new release v1.1.0 and it includes the fix for the performance issues you were experiencing, you can download it from [here](https://github.com/aws/aws-gamekit-unreal/releases/tag/v1.1.0).

**Comment by zorigoo0128** [comment]
Thank you Adrián!
