### ISSUE TITLE
Feature Request: Unreal Engine 5

### ISSUE THREAD

**Issue by TannerIsBender** [aws/aws-gamekit-unreal#5]
Hello,

This is an awesome plugin!! Would it be possible to update the plugin to support UE5.

If you really wanted to make this more amazing than it already is, could it be possible that the UE5 Sample works with the Lyra Sample Base provided by epic?

Thanks!!!

**Comment by Jordonbc** [comment]
Hello TannerIsBender,
I have ported a version of this to UE5: [https://github.com/Jordonbc/aws-gamekit-unreal/tree/UE5](https://github.com/Jordonbc/aws-gamekit-unreal/tree/UE5).

I would send them a PR but they aren't accepting community edits.

**Comment by TannerIsBender** [comment]
Thank you @Jordonbc I will definitely check it out this weekend

**Comment by AMZN-kevomara** [comment]
Hello TannerIsBender,

I'm glad you're enjoying the plugin!

We will be working on supporting UE5 soon. We are also planning to create a demo game.

We haven't tried integrating AWS GameKit with the [UE5 Lyra Sample Game by Epic](https://docs.unrealengine.com/5.0/en-US/lyra-sample-game-in-unreal-engine/). So I'm not certain whether they work together.

I'll re-open this issue and leave it open until we add support for UE5.

**Comment by Held0fTheWelt** [comment]
Didn't see it here ! But yeah, it's working well in UE5.
Just needs a little change and a recompile !
As mentioned by amzn-proothia:
https://github.com/aws/aws-gamekit-unreal/issues/10

**Comment by falbellaihi1** [comment]
adding to what amzn-proothia #10. Although at the time of this post the only thing I did was changing engine version && modifying this line in .uplugin 
`		{
			"Name": "AwsGameKitRuntime",
			"Type": "Runtime",
			"LoadingPhase": "EarliestPossible",
			"WhitelistPlatforms": [
				"Win64",

			]
		},`
		
For some reason, when it was Default, I was getting Failed to load 'AwsGameKitRuntime' which results in all functions and structs being missing after each restart.

**Comment by amzn-adrian** [comment]
Hi,

We've released an updated version of the plugin with support for Unreal Engine 5, you can find it [here](https://github.com/aws/aws-gamekit-unreal/releases/tag/v2.0.0).
