### ISSUE TITLE
After removing intermediate and saved folders it crashes on Startup of the Project

### ISSUE THREAD

**Issue by DevGarou** [aws/aws-gamekit-unreal#7]
I configured my project correctly with identity and UsergameplayData modules and it worked fine until I removed the Intermediate and Saved folder to make some space and because I needed a clean state to dev upon it and here is the problem I saw: 
On Launch it triggers a breakpoint in AwsGameKitCredentialsLayoutDetails.cpp line 974 because the LastUsedEnv variable is empty.:

```
FString const lastUsedEnv = editorModule->GetFeatureResourceManager()->GetLastUsedEnvironment();

const auto lastUsedEnvironmentList = environmentOptions.FindByPredicate([this, lastUsedEnv](const FComboBoxItem comboBox) { return (*comboBox.Get() == environmentMapping[lastUsedEnv]); });
```

I hope that can be fixed soon because it's actually blocking the whole plugin on the editor side.

**Comment by schichko** [comment]
Hey DevGarou,

I am with the GameKit team and I tried to reproduce your issues with the newest release but unfortunately could not get to the same state that you are in. 

It would also help if you can provide the following information

1. Unreal Editor Version [e.g. 4.27.2]
2. IDE and Version [e.g. Visual Studio 2019 16.11.7]
3. OS and Version that you are developing on: [e.g. Windows 10]

**Comment by DevGarou** [comment]
Actually I did more than just remove Intermediate and Saved Folder, I
runned this script to clean my project (clean.bat in copy)
I think it removed the Libraries folder too but even when I add it back it
still crashes there:
I think it's strange that the settingsInstanceHandle is null at this point,
it seems like some dependencies are not loaded correctly



https://gyazo.com/d3479680fd50d2447ae68f5b508144bb

Clean.bat code: (to paste in a new file
@ECHO off

REM This command cleans the given project's folder and calls clean.bat for
each plugin, if it exists. If it does not exist, it will default-clean that
folder.

REM Usage: Clean

ECHO Default cleaning..
RD /s /q .vs
RD /s /q Binaries
RD /s /q Build\WindowsNoEditor
RD /s /q Build\LinuxNoEditor
RD /s /q Build\LinuxServer
RD /s /q Debug
RD /s /q DerivedDataCache
RD /s /q Intermediate
MKDIR Temp
MOVE Saved\Config\Windows Temp\
RD /s /q Saved
MKDIR Saved\Config
MOVE Temp\Windows Saved\Config\
RD Temp
MKDIR Saved\Logs
REM RD /s /q Packaged
REM RD /s /q Releases
DEL /f "*.sdf"
DEL /f "*.sln"
DEL /f "*.db"


ECHO Cleaning plugins..
REM For each existing plugin, we call Clean.bat if it exists, otherwise we
simply remove Binaries, Intermediate and Saved
IF EXIST Plugins (
CD Plugins
FOR /D %%f IN (.\*) DO (
ECHO Cleaning %%f
PUSHD %%f
IF EXIST "Clean.bat" (
call Clean.bat
) ELSE (
rd /s /q Binaries
rd /s /q Intermediate
rd /s /q Saved
)
POPD
)
CD ..
)

ECHO Cleaning empty folders in Source..
ROBOCOPY Source Source /S /MOVE

ECHO ----
ECHO Done
ECHO ----

Thank you

**Comment by schichko** [comment]
I am glad to hear that fixed your issue. I believe the root cause was the following section in the Clean.bat script you sent above:
```
CD Plugins
FOR /D %%f IN (.\*) DO (
ECHO Cleaning %%f
PUSHD %%f
IF EXIST "Clean.bat" (
call Clean.bat
) ELSE (
rd /s /q Binaries
rd /s /q Intermediate
rd /s /q Saved
)
```
Since we do not have a Clean.bat script in our plugin directory I believe that the needed binaries were removed which caused the dlls to not be loaded like you mentioned. On our end we can look into creating a Clean.bat script within our plugin directory that can prevent this issue from happening in the future.

If you ever run into an issue like this again you may want to consider re-building and copying over the dlls from out C++ plugin. This is also useful if you ever want to change the functionality of our libraries.
https://github.com/aws/aws-gamekit 

Please feel free to re-open this issue if you run into any more issues with this.

**Comment by DevGarou** [comment]
Hi again, I did run into this issue again and here what fixed the dll loading issue for me: 
I added that line in ..\AwsGameKitCore\Private\Core\AwsGameKitLibraryWrapper.cpp line 32 to actually pass the full path to the dll instead of just the filename: 
`    libraryPath = FPaths::Combine(FPaths::ProjectDir(), TEXT("Binaries"), TEXT("Win64"), libraryPath);`

**Comment by DevGarou** [comment]
Although if you want to fix another problem it would be nice to have no
crash a the end of an editor session.
The editor is crashing when we close it because a lambda is called but not
existing anymore somewhere in your code.
Here is a photo:
[image: image.png]

Thanks a lot!

Otherwise really good job it's really handy!
