### ISSUE TITLE
aws-gamekit-unreal available for linux?

### ISSUE THREAD

**Issue by DevGarou** [aws/aws-gamekit-unreal#8]
Hello, I would like to use this game kit for a multi player game and have my linux server do some interactions wiht the database.
Is it possible easily to compile all this plugin for lInux or even provide a realease that is compatible with Linux?

Thank you

**Comment by AMZN-kevomara** [comment]
Hi DevGarou, we haven't tested compiling GameKit for Linux yet. We've only tested for Windows, Mac, iOS, and Android. If you'd like to give it a try yourself, it might "just work" because Linux and Mac are similar.

**Comment by DevGarou** [comment]
Hi AMZN-kevmora thank you for that, I will see if I have some time to try that soon.
Otherwise is there a plan to support linux in the near futur?

**Comment by amzn-proothia** [comment]
Hi DevGarou,
We will keep this under consideration for our upcoming feature updates.
